// <auto-generated />
using BootstrapTableDemo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BootstrapTableDemo.Migrations
{
    [DbContext(typeof(EditableDemoDBContext))]
    partial class EditableDemoDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BootstrapTableDemo.Models.EmployeeList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Department");

                    b.Property<string>("DepartmentsName");

                    b.Property<int>("Gender");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("EmployeesList");
                });

            modelBuilder.Entity("BootstrapTableDemo.Models.InfoDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("InfoDepartments");
                });

            modelBuilder.Entity("BootstrapTableDemo.Models.InfoEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Department")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("Department");

                    b.ToTable("InfoEmployees");
                });

            modelBuilder.Entity("BootstrapTableDemo.Models.InfoEmployee", b =>
                {
                    b.HasOne("BootstrapTableDemo.Models.InfoDepartment", "Departments")
                        .WithMany("Employees")
                        .HasForeignKey("Department")
                        .HasConstraintName("FK_InfoEmployee_InfoDepartment")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
